### ISSUE TITLE
NameError: name 'ensure_punkt' is not defined

### ISSUE THREAD

**Issue by danielw97** [aedocw/epub2tts#103]
Hi again,
Getting the following error after pulling the most recent changes.
As such, I've reverted to the previous commit for now.
Is there something special I have to do, as punkt is already downloaded in my case?

Traceback (most recent call last):                                                                                      
  File "C:\Users\daniel\Documents\epub2tts\epub2tts.py", line 419, in <module>                                          
    main()                                                                                                              
  File "C:\Users\daniel\Documents\epub2tts\epub2tts.py", line 408, in main                                              
    mybook = EpubToAudiobook(source=args.sourcefile, start=args.start, end=args.end, skiplinks=args.skiplinks, engine=args.engine, minratio=args.minratio, model_name=args.model, debug=args.debug)                                             
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             
  File "C:\Users\daniel\Documents\epub2tts\epub2tts.py", line 67, in __init__                                           
    ensure_punkt()                                                                                                      
    ^^^^^^^^^^^^                                                                                                        
NameError: name 'ensure_punkt' is not defined

**Comment by aedocw** [comment]
Ooof embarrassing! Very sloppy testing on my side, and trying to do too many things at once tonight. Thanks for catching that, it should be fixed in main now.

Thanks again for letting me know!

**Comment by danielw97** [comment]
No problem at all, cheers for fixing so quickly.
