### ISSUE TITLE
ability to exit gracefully after generating flacs?

### ISSUE THREAD

**Issue by danielw97** [aedocw/epub2tts#122]
Hi,
Not sure how easy this is, although I don't suppose it might please be possible to add a flag at some point in the future which if defined would cause epub2tts to exit gracefully after all flacs are generated (prior to concatenating all parts for the m4a)?
This might not be the most apparent, although it's useful if people want to do further processing.
In my case I have several long books that are failing at the step where they are exported to m4a, and I've started bringing the flacs into my audio editor of choice, doing some post-processing and then exporting with chapter marks from there.
Right now I'm manually canceling after all parts are spoken, although figure it's worth bringing up.
Thanks in advance, and let me know if more info would be useful here.

**Comment by aedocw** [comment]
This is *super* easy, I'll just add it to "debug", so if you specify "--debug" you get a whole lot more output, but it would be trivial for me to NOT delete the chapter flac files if debug flag was specified. I can do this in the next half hour.

**Comment by danielw97** [comment]
That is superb, thanks so much for doing this so quickly.
