### ISSUE TITLE
Add ability to take plain text file as input

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#13]
It would be nice if the script took a guess at what the input file type was based on the extension, and was able to handle plain text files. Other than determining where chapter breaks might be so as to cut this up into small enough chunks for Coqui-TTS, this should be pretty easy to implement.

**Comment by tissatussa** [comment]
You're right, that would be handy, but this is a script for ePub files .. i created an ePub file from a normal text by using Libre Office (on Linux) and exporting to ePub, simple.

**Comment by aedocw** [comment]
You are correct that the original intent was to handle epub files, but I've realized I also have some very long articles from the web that I would like to have turned into audiobooks, so being able to throw a .txt file at it would be pretty nice.
