### ISSUE TITLE
Can not run on GPU

### ISSUE THREAD

**Issue by Simorg2002** [aedocw/epub2tts#14]
The programs works fine, but from the task manager I only see spikes in CPU usage when it starts.

The closest issue I could find was https://github.com/coqui-ai/TTS/discussions/2267 , but they are talking about the training part, while I'm going for simple tts from a base model.

Trying:
`import torch
torch.cuda.is_available()`
before returned false, but that was fixed by reinstalling torch and torchaudio, so they now recognize my GPU. (also checked compatibility with cuda version using `nvidia-smi` )

Still, even when adding --use_cuda or gpu=True flags to epub2tts.py in the TTS call, I can see no GPU usage. Am I doing something wrong?
I'm no dev and I would not be surprised if I was just adding arguments in the wrong place or something, but this really has me confused as I have been playing around with stable diffusion with no issues.

**Comment by aedocw** [comment]
Apologies for the late response, just noticing this issue.

I am not sure. I have not been running this on a machine with GPU, have mostly been using an older intel linux box for encoding, and occasionally running on an m1 macbook, so I have not had an opportunity to try this with cuda. Your best best would probably bet to ask about this on coqui discord server. I imagine this must go *much* quicker with a GPU available.
