### ISSUE TITLE
ubuntu 20.04 too old?

### ISSUE THREAD

**Issue by rejuce** [aedocw/epub2tts#143]
out of desperation that the docker container had no CUDA support, i tried the direct install route over  pip install .  from the repository, but failed with manye errors that dependencies could not be fulfilled because available ones werere too old. trying now with differnt instance on ubuntu 22.04

**Comment by aedocw** [comment]
I have never tried with anything other than ubuntu 22. I do know for sure that WSL with ubuntu 22 has cuda support as long as cuda 11.8 is installed (https://developer.nvidia.com/cuda-toolkit-archive).

**Comment by rejuce** [comment]
sorry for the misunderstanding, I tried to install epub2tts directly (with pip...) without docker under 20.04, which fails

under 22.04 no problem

**Comment by aedocw** [comment]
Yes, I believe Ubuntu 20 is too old for this.
