### ISSUE TITLE
250 char token size exeeded

### ISSUE THREAD

**Issue by rejuce** [aedocw/epub2tts#151]
sometimes, seldomly I see: 

 > Text splitted to sentences.
["Mary and Souji's eyes narrowed.", "Paying no mind to the two of them, Genia continued, “My family has studied curse ore for many long years. You could say our discovery of its ability to steal and store magic's power was the result of intergenerational research. During all our time studying it, I had one constant doubt,  If magic was the result of magicium, what exactly was curse ore?”", 'No one answered her question, so Genia elaborated.', '“I had a vague idea.']
[!] Warning: The text length exceeds the character limit of 250 for language 'en', this might cause truncated audio.

**Comment by aedocw** [comment]
This comes up sometimes but usually has no impact on the output.

Can you paste the full command you are calling it with, just so I can make sure there's nothing off?

**Comment by rejuce** [comment]
python3 /home/jk/epub2tts/epub2tts.py ~/epubconvert/myepub.epub --start 4 --end 4 --engine xtts --speaker "Baldur Sanjin"  for example

**Comment by aedocw** [comment]
Oh right! Thanks, I forgot that using Coqui speakers, it could show this warning. I have seen the warning lots of times with this path but have never noticed any truncated audio. If you do catch it actually cutting off audio please let me know, there's a part I can adjust where it will send even smaller sentence sets.

**Comment by aedocw** [comment]
Closing this, as I don't think there's anything to fix at this time.
