### ISSUE TITLE
after most recent murge, epub2tts fails to process a file

### ISSUE THREAD

**Issue by danielw97** [aedocw/epub2tts#165]
Hi,
Some really interesting development happening with being able to hopefully process markdown in the future, however after the most recent murge epub2tts fails to convert an epub, and exits after computing the number of chapters to read.
I've tested with xtts so far, although let me know if testing with anything else would help.
I'm now running on wsl with cuda support if that makes a difference.

**Comment by aedocw** [comment]
Haha no so sorry - I just realized I was in too much of a rush and did not properly test! I'm reverting that last commit until it's working and fully tested. Ugh, every time I think I'm making a simple change and skip the testing, I break something!

**Comment by aedocw** [comment]
Should be fixed now, sorry for that, please let me know if issues persist.
