### ISSUE TITLE
after murging the ffmpeg-concat branch, unable to use a title with an apostrophe

### ISSUE THREAD

**Issue by danielw97** [aedocw/epub2tts#182]
Hi again,
The new changes are working great, however one issue I've noticed is that ffmpeg doesn't seem to like a title with an apostrophe (') in it.
I'm not sure if there is a way to work around this, or if it's just a case of removing the apostrophe before starting.
Things are working well otherwise and thanks again for your help in sorting this.

**Comment by aedocw** [comment]
Oh great catch! I've always been in such a habit of removing all punctuation and spaces and stuff from filenames that I don't run across stuff like this.

I added a replacement to escape single quotes in filenames for ffmpeg concat, branch is "pesky-punctuation". Worked in my testing, let me know if it solves the issue for you.

**Comment by danielw97** [comment]
Thanks for looking at this so quickly.
I'm still getting the impossible to open error when it gets to the concat stage, and I'm on the pesky-punctuation branch.
If it's easier I can just remove the apostrophe from the title, although imagine someone else will come across this in future.

**Comment by aedocw** [comment]
Oh that's weird! Could you share the exact file name that seems to be causing problems?

**Comment by danielw97** [comment]
Hi again,
I've just tested using the pesky-punctuation branch and not sure what was going on earlier, but it is working now.
Cheers for the quick fix.

**Comment by aedocw** [comment]
Success!! You should go ahead and take the rest of the day off ;)

(thanks as always for your help and collaboration!)
