### ISSUE TITLE
Bring back Realtime factor

### ISSUE THREAD

**Issue by rejuce** [aedocw/epub2tts#186]
I found it very useful that after each junk the Realtime factor was displayed. It was easy to compare different hardware with that. Since the ffmpeg merge that one is gone.

Tried with - - debug but not there either

**Comment by danielw97** [comment]
Hi,
Aedocw may have more info on this, but at least for me the realtime factor is still there.
Ffmpeg is only used at the last step when the m4b is created from the wavs, and has no impact on the synthesis to my knowledge.

**Comment by aedocw** [comment]
You would see that with VITS model for instance:
```
 >  Processing time: 11.560602903366089
 > Real-time factor: 0.2379075645646571
```
but with XTTS (whether you're cloning a voice yourself, or using Coqui studio voices), that code uses their streaming interface which allows for use of deepspeed so for some folks it will be anywhere from 2x to 4x faster.

You can get a sense of speed during runs by watching seconds-per-iteration, which will be all the way to the right on each line while it runs.

**Comment by rejuce** [comment]
since the switch to the streaming API i get something linke this 

![grafik](https://github.com/aedocw/epub2tts/assets/28755821/8873045f-eed8-4483-94c3-ad91eebbcdad)

do you know how it/s translates to realtime factor? the value seems to vary widely
