### ISSUE TITLE
instructions don't cd back to project root

### ISSUE THREAD

**Issue by sweth** [aedocw/epub2tts#2]
instructions say to cd into venv dir to source bin/activate, but that means that user isn't at project root when they try to do the pip3 install, and thus requirements.txt isn't found

**Comment by aedocw** [comment]
The instructions have you clone the project into epub2tts, create a venv in epub2tts, the cd into epub2tts. Activating the venv and then running pip3 install there will work, BUT it's bad practice to have created the virtual environment in the project root like that, and you'll end up creating a bunch of stuff you don't want tracked in the repo. I'll adjust the instructions for a more sane/normal approach, thanks for noticing that!
