### ISSUE TITLE
Part/Chapter titles mismatch

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#209]
When using a text file with chapter titles (`# one` etc), if you specify `--start N`, the FFMETADATA file will be created starting from the first chapter no matter what.

Expected behavior is for the chapter titles in FFMETADATA should start with whichever chapter you asked it to start on.

**Comment by calledit** [comment]
This bug is fixed in this commit:
https://github.com/aedocw/epub2tts/pull/259/commits/c94d8adae0865380c74f2299a323819c1c5d94c9
