### ISSUE TITLE
Possible to use edge tts or local spd-say?

### ISSUE THREAD

**Issue by jpenguin** [aedocw/epub2tts#210]
https://github.com/p0n1/epub_to_audiobook allows the use of free cloud-based edge tts.  It isn't as good as coqui, but being cloud based is very fast.

I also have several voices from https://www.oralux.org/, I can use with spd-say on linux.  Is it possible to use these?

**Comment by aedocw** [comment]
That's really interesting, I use Audiobookshelf but had not see epub_to_audiobook, it looks really nice!

I'll play around with it, and edge, and see if it makes sense to incorporate it. The default voice does sound decent, and means this is available to create an audiobook quickly for folks who do not have a GPU. Thanks for pointing me to this, I'll update here when I've got time to work on it (it should be pretty straightforward to add edge).

**Comment by aedocw** [comment]
Adding edge-tts now under https://github.com/aedocw/epub2tts/issues/220

**Comment by aedocw** [comment]
I'm closing this, as I do not plan to add spd-say since it's linux only, and I want this to work basically the same on linux, windows and macos. I *did* add support for edge, and wish I had done it sooner as it's pretty excellent, thanks for suggesting it!
