### ISSUE TITLE
Update instructions unclear

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#212]
It's not obvious how users are supposed to update this application. The steps are straightforward, but if you're not familiar with python and pip there's no way you would guess this. The README should be updated to tell users to:

1. cd to repo directory
2. `git pull`
3. Activate virtual environment you installed epub2tts in
4. `pip install . --upgrade`

**Comment by larry77** [comment]
When I made the Linux instalation I used the command pip install . without resorting to a virtual environment. So perhaps I would need some update on the installation instructions for Linux. Not an expert on pip and virtual environment

**Comment by aedocw** [comment]
README has been updated.
