### ISSUE TITLE
Conversion to text file adds in spaces inside of words and add extra punctuation where it is not supposed to be.

### ISSUE THREAD

**Issue by Nikanoru** [aedocw/epub2tts#216]
Hello!

A friend asked me if I could do another epub to audio with your program for him and I encountered some issues with the epub -> txt conversion.

It seems in the first sentence of every new part, there is an added space inside of a word. 
So for example instead of "Word" it will be "W ord". 
And also the "-" or "--" characters seems to sometimes? turn into ","

I wasn't sure if there is something wrong with the epub or the conversion process, and it seems it is indeed the latter. I tried a different program to do the conversion and indeed the extra spaces and extra punctiation was not there, but unfortnately the nice "Part Feature" is not availible there.

I included a few screenshots to highlight what I mean. Left side of the picture is from epub2tts and right side is the other program (https://github.com/kevinxiong/epub2txt).

![Screenshot 2024-03-01 140229](https://github.com/aedocw/epub2tts/assets/83954293/4fdf7ee1-3dd5-4b86-8c8b-3cf222c3e871)
![Screenshot 2024-03-01 140417](https://github.com/aedocw/epub2tts/assets/83954293/a363c41d-6544-41ee-8ccc-cc7479dd206f)
![Screenshot 2024-03-01 140544](https://github.com/aedocw/epub2tts/assets/83954293/fc5de47d-d15e-45d2-ae5b-edcc984852a0)

**Comment by aedocw** [comment]
I'm adding `--skip-cleanup` as an option that, if specified, will not remove special characters. It should help with what you ran into.

**Comment by Nikanoru** [comment]
I hope it's not an issue if I respond here, I am not sure about the workings of Github with closed issues, so I hope it's not a problem. 

Thank you for your swift action on this issue :) 

I wonder, since the 2 different programs I tested for epub -> txt did not create those extra spaces, would it be possible to get inspiritation from them? I am not sure how all this works, but both programs are open source here on github.

Anyways, great to see you are still working on your program and helping folks out. :) If there will ever be a possibility of providing you some financial thanksgiving :P please let me know.

**Comment by aedocw** [comment]
I will take a look when I get a chance and see if I find any inspiration :)
