### ISSUE TITLE
Can edge TTS be incorporated?

### ISSUE THREAD

**Issue by inolie** [aedocw/epub2tts#220]
https://github.com/rany2/edge-tts/

I found the edge voices more natural and easy to listen to. would be great to incorporate.

**Comment by aedocw** [comment]
Wow you are right, the quality on this is excellent. IMO it's not as good as XTTS in terms of sounding natural, but it's not far off. The best thing is this does not require a GPU or even much CPU to get excellent output. I don't know how/why MS is letting folks use their compute for free like this, but might as well jump on it!

I will work on adding this soon, thanks for the suggestion!

**Comment by aedocw** [comment]
I've added a branch for testing with edge (add-edge-tts) and am running through a book tonight. Still need to update the README with instructions, and I haven't tested using a different voice other than the one I set to be default (en-US-AndrewNeural) but you should be able to specify any edge speaker with `--speaker <speaker>`. You can use edge by specifying `--engine edge`.

**Comment by jpenguin** [comment]
Wonder how long MS will keep this free?  Pretty nice.  Three languages, one file:
`epub2tts ./sample2.txt --engine edge --sayparts  --speaker en-US-BrianMultilingualNeural `

https://app.box.com/s/fq4sbr4r0nnooa2cht78rcdlvpmdj1wn
