### ISSUE TITLE
PopOS/Ubuntu installation

### ISSUE THREAD

**Issue by michaelachrisco** [aedocw/epub2tts#224]
I wa able to get this project working on an old PopOS machine that can barely run the Cuda work. Thought I would share the instructions on how I did it. Its a slight variation of the Linux install instructions: 

`sudo apt install nvidia-cuda-toolkit` is the biggest change. Makes it easy to pull in for pop.

```
#install dependencies
sudo apt install espeak-ng ffmpeg nvidia-cuda-toolkit
#clone the repo
git clone https://github.com/aedocw/epub2tts
cd epub2tts
python3 -v venv venv
source venv/bin/activate
pip install .
```

Some distros like to default to py2 still. using the venv makes sure the install uses py3 and stays self contained. So I added:
(Optional)
```
python3 -v venv venv
source venv/bin/activate
pip install .
```

Im not sure if you want to add it to the repo or not, but just wanted to share! Thanks again for the library!

**Comment by aedocw** [comment]
Thanks! I did mention the CUDA toolkit, but it was in a note regarding deepspeed. This was a good suggestion so I added it as an optional step in the linux install instructions.
