### ISSUE TITLE
Add a little pause between paragraphs

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#232]
When creating audiobooks, the way text is extracted from the epub just squashes each chapter together, ignoring paragraph breaks. Books definitely sound better if there's a little pause between each paragraph.

There are probably way better ways of approaching this, but the code has become kind of an embarrassing nightmare at this point, so I'm just going to yolo this...

If you add `--parapause` when exporting to text, it will add a `%P%` between each paragraph in the text file that is output. ONLY with `--engine edge`, if %P% is detected, a 1.2 second pause will be prepended to the wav file for that sentence. It seems to work pretty nicely, but I do not plan to merge this quite yet. But it's working pretty nicely for me so far :)

**Comment by aedocw** [comment]
Rather than inserting %P% for paragraph breaks, epub2tts should just recognize empty lines. Then when exporting, it should insert an empty line between each paragraph. In addition, when reading directly from epub files it should recognize the paragraph breaks the same way and insert an additional brief pause between each paragraph.

**Comment by aedocw** [comment]
This has been incorporated into https://github.com/aedocw/epub2tts-edge/ instead.

**Comment by vtennero** [comment]
Hello, what's the command for this?
also it looks like epub2tts-edge doesnt support voices like epub2tts

**Comment by aedocw** [comment]
This feature was never merged. I had mostly stopped working on this one in favor of epub2tts-edge. I do appreciate that you can't use XTTS voice clones with that one, but I don't really have much time any more to devote to either project.

I'm happy to merge improvements for any useful PRs that come along though.
