### ISSUE TITLE
Multiple voice handling

### ISSUE THREAD

**Issue by mkaflowski** [aedocw/epub2tts#235]
Handling multiple voices would be great feature to generate audiobooks. It could handle text like:
```
{voice1}- Hello. I am character A {/voice1}
{voice2}- Hello. I am character B {/voice2}
```

**Comment by aedocw** [comment]
That would be neat, but would also require a massive overhaul of the codebase, so this will not be implemented here. Take a look at https://github.com/DrewThomasson/VoxNovel though, that might fit your needs.
