### ISSUE TITLE
[Request] Add system requirements section in the README for each of the TTS engines

### ISSUE THREAD

**Issue by rpgdev** [aedocw/epub2tts#248]
It's not clear to me if I can even test this effectively on my laptop with integrated GPU and I think that's going to be the case for anyone who isn't too well versed on the technical side of AI. It'd be great if there was a section in the README with the recommended system requirements for each TTS engine. There's mention of "VITS model is the fastest, does not require GPU" but what about the others? What are the implications of not having GPU for the others? How long would it take? etc.

**Comment by aedocw** [comment]
Unfortunately there's no easy way to answer whether or not your laptop GPU is usable with XTTS. Even [on their docs](https://docs.coqui.ai/en/latest/models/xtts.html), I don't see a clear "minimum GPU requirements".

You can pretty easily check for yourself by installing epub2tts in a venv and seeing what the performance is like for reading a very small text file.
