### ISSUE TITLE
Docker's Ubuntu version should not be "latest"

### ISSUE THREAD

**Issue by darauble** [aedocw/epub2tts#251]
Trying to build the docker image from Dockerfile fails, as the latest Ubuntu version as of this ticket time is 24.04. TTS cannot be found in pip sources and there are failure because much of the Python3 is managed by apt.

Changing the first line to `from ubuntu:22.04` (as per readme :-) ) works just fine. This should be the case for all "stabilized" software, "latest" is never a good idea...

Cheers, except for some small quirks this is really a good solution! Amazon Polly would be also a nice addition ;)

**Comment by aedocw** [comment]
Thanks, that's a good point!
