### ISSUE TITLE
Missing punkt_tab

### ISSUE THREAD

**Issue by darauble** [aedocw/epub2tts#252]
Commit 5f9ffda8db9e2ce670074fbdb444c685dc6d696f.

Changed Dockerfile to ubuntu:22.04 (as reported in the issue #251) and tried to run the application. It failed wit:

```
 Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
```

Added to the code:

```
    def ensure_punkt(self):
        try:
            nltk.data.find("tokenizers/punkt")
        except LookupError:
            nltk.download("punkt")
        try:
            nltk.data.find("tokenizers/punkt_tab")
        except LookupError:
            nltk.download("punkt_tab")
```

It works.

**Comment by DontBlameMe99** [comment]
Fix for me: Just start python and do what it says -` import nltk` and `nltk.download('punkt_tab')` - then exit python using `exit()`. After that it worked for me!
