### ISSUE TITLE
Error cythonizing spacy on pip install TTS

### ISSUE THREAD

**Issue by rafferty90** [aedocw/epub2tts#269]
pip install TTS thows the error "Cython.Compiler.Errors.CompileError: spacy/kb.pyx" (spacy-3.0.6.tar.gz). Any thoughts on how to resolve this? :)

![error1](https://github.com/user-attachments/assets/1aa82569-0be4-4161-aefc-3728639e1769)
![error3](https://github.com/user-attachments/assets/b6c6e864-f8c1-4adc-ae57-aaab26ea345f)

**Comment by Drivez** [comment]
I get the same error when trying to install

**Comment by aedocw** [comment]
What platform? Which version of python?

I haven't done a clean install in ages but I'm trying now (so far its going fine but also taking ages to download so many versions of transformers!!)

**Comment by Drivez** [comment]
Im on Mac using a dev container with python 3.11

**Comment by rafferty90** [comment]
Mine is windows 10, python 3.11. I do not have a dedicated gpu so I have opted and successfully used the edge-tts version. Very happy with the results. This being my first tts project. I have learnt a lot. @aedocw if you have any insights on how to solve this, this will be great.

**Comment by aedocw** [comment]
I had a successful TTS install on a mac, in a virtual environment, with `Python 3.11.2`. It took a *long* time.

I'm running a fresh install of TTS on an Ubuntu 22 machine with `Python 3.10.12`, so far it's going OK but also taking ages...

**Comment by Drivez** [comment]
UPDATE: i tested this on another Mac not using the M chips and it worked fine, so maybe something there? or something other our local machines

**Comment by aedocw** [comment]
I just recreated this error on a clean Ubuntu 24.04 system with python 3.11.10 in a venv. Damn :(

I'll see if I can figure out why, but if anyone has ideas or sorts this out, please share, thanks!

**Comment by aedocw** [comment]
I think this fixed it for me: `pip install -r requirements.txt --only-binary spacy`

Before that, in the same venv, I ran `pip install spacy --only-binary spacy`, but I *think* you can just use the first thing alone to tell pip to install everything in requirements, but only install binary of spacy instead of trying to compile locally.

**Comment by nowjon** [comment]
> I think this fixed it for me: `pip install -r requirements.txt --only-binary spacy`
> 
> Before that, in the same venv, I ran `pip install spacy --only-binary spacy`, but I _think_ you can just use the first thing alone to tell pip to install everything in requirements, but only install binary of spacy instead of trying to compile locally.

Windows 11, Python 3.11.9
I attempted these commands, still getting this error

(.venv) PS C:\users\Jon\Development\epub2tts> pip install .
Processing c:\users\jon\development\epub2tts
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting beautifulsoup4 (from epub2tts==2.6.0)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting deepspeed (from epub2tts==2.6.0)
  Using cached deepspeed-0.15.2.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      ←[93m [WARNING] ←[0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "C:\users\Jon\Development\epub2tts\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\users\Jon\Development\epub2tts\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\users\Jon\Development\epub2tts\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Jon\AppData\Local\Temp\pip-build-env-gxmv78xd\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Jon\AppData\Local\Temp\pip-build-env-gxmv78xd\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Jon\AppData\Local\Temp\pip-build-env-gxmv78xd\overlay\Lib\site-packages\setuptools\build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Jon\AppData\Local\Temp\pip-build-env-gxmv78xd\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by onura46** [comment]
The [TTS library used by this repo isn't supported anymore](https://github.com/coqui-ai/TTS/issues/4029#issuecomment-2418623945). People are having similar issues over there, so I expect the problems are similar here. They recommend switching to `coqui-tts` where it's being maintained now.

**Comment by aedocw** [comment]
I'm trying with [this repo](https://github.com/idiap/coqui-ai-TTS), replacing TTS with coqui-tts in requirements. Will follow up with how that goes.

**Comment by aedocw** [comment]
Thanks to @onura46 I think the fix was switching to a new repo for coqui! Merging update to requirements now, users experiencing failed installs can try `pip install . --upgrade --force-reinstall` after pulling the branch `switch-tts`. Feedback welcome!

**Comment by aedocw** [comment]
This worked with this branch and Python 3.11 in a clean venv:
```
pip install coqui-tts --upgrade --force-reinstall --only-binary spacy
pip install .
```

I'll update instructions, I think it's fixed! Folks who have had problems, please try and let me know how it works for you.

**Comment by danielw97** [comment]
Thanks a bunch for this.
Whilst I wasn't having this particular problem, I was seeing some dependency issues with the old unmaintained version of tts.
This particular fork is actively being contributed to it seems as well which is a big help.
