### ISSUE TITLE
Slow performance with XTTS and GPU

### ISSUE THREAD

**Issue by arashonfire** [aedocw/epub2tts#272]
First, thank you for the great work. The result is incredible, and I have already started listening to and enjoying the generated Audiobooks.

When I use the TTS engine, the speed is very good. It can do a couple of chapters in a couple of minutes. But when I switch to XTTS, it uses GPU automatically, and the performance is sluggish. Each chapter takes half an hour. I have a good GPU (16 GB VRAM) and a great CPU, and I am running it on Ubuntu 24.04 with 32 GB of RAM. Of course, the quality of XTSS-generated audio is much better than TTS.

My questions:
1) Is it normal for XTTS to be much slower?
2) Can I run XTTS without GPU?
3) XTTS only asks for a small amount of RAM (300 MB). Is it normal?
```
Detected CUDA files, patching ldflags
Emitting ninja build file .cache/torch_extensions/py311_cu124/transformer_inference/build.ninja...
Building extension module transformer_inference...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer_inference...
Time to load transformer_inference op: 0.048979997634887695 seconds
VRAM: 16848846848
Free memory : 8.592285 (GigaBytes)  
Total memory: 15.691711 (GigaBytes)  
Requested memory: 0.335938 (GigaBytes) 
Setting maximum total tokens (input + output) to 1024
``` 
Thanks!

**Comment by aedocw** [comment]
Yes, XTTS is going to be slow. Performance of that will vary greatly by GPU. If deepspeed is installed/available it will improve the performance, but I can't say by how much.
