### ISSUE TITLE
trouble using local openai endpoint, name not defined

### ISSUE THREAD

**Issue by danielw97** [aedocw/epub2tts#273]
I'm not 100% sure when this started, but assume it must be after the most recent refactor.
I'm using a local openai endpoint if I want tts other than coqui (this utility).
https://github.com/matatonic/openedai-speech
Currently though, I'm getting the following error which I didn't receive in the past:
Traceback (most recent call last):                                                                                      
  File "/home/daniel/epub2tts/.venv/bin/epub2tts", line 33, in <module>                                                 
    sys.exit(load_entry_point('epub2tts==2.6.0', 'console_scripts', 'epub2tts')())                                      
  File "/home/daniel/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 1176, in main                       
    mybook.read_book(                                                                                                   
  File "/home/daniel/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 903, in read_book                   
    map_result = list(map(process_book_chapter, chapter_job_que))                                                       
  File "/home/daniel/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 340, in process_book_chapter        
    tts_engine.proccess_text_retry(text, file_name)                                                                     
  File "/home/daniel/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 81, in proccess_text_retry          
    self.proccess_text(text, wave_file_name)                                                                            
  File "/home/daniel/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 129, in proccess_text               
    response.stream_to_file(wave_file_name)                                                                             
NameError: name 'response' is not defined                                                                               
Is there a way to troubleshoot this, and hopefully please get it fixed at some point?
Edit: tested with commit 303cb6b4d49df0ee1327ae26d07e7adf4f0adf37 and the conversion works fine.
I know this is very low priority as using a local api isn't within the scope of most users, but wanted to document it here in case anyone has any suggestions.
Using python 3.10 on wsl, and latest version of epub2tts.
Thanks in advance.

**Comment by danielw97** [comment]
@aedocw Just raising this again, as I've been troubleshooting and this also happens with the real openai tts endpoint as well, so might be something broken from the refactor?
I'm not sure if anyone would be willing to take a look, but I'm always happy to test builds and report back.

**Comment by aedocw** [comment]
Sorry, I've been buried with the real job lately and haven't had a chance to look at this. I also haven't touched OpenAI since I first added this. I'll keep this open and I'm sure at some point I'll want a distraction and I can play with it and sort out whatever broke.

**Comment by danielw97** [comment]
Thanks a lot, I completely understand getting busy and appreciate all the work you've done on this.
Here's hoping it can be looked at one day, no rush of course though.

**Comment by CosmicWatcher** [comment]
I also ran into this issue and the fix is very simple. In the file epub2tts.py on line 124 where you have `self.client.audio.speech.create(` you just have to save the incoming data into the response variable. So just change the line to make it `response = self.client.audio.speech.create(`

**Comment by danielw97** [comment]
Thanks a lot for that explanation, your suggested change has fixed it for me.
