### ISSUE TITLE
Read Along: EPUB3 output or export synchronization data (SIML) to sync audio and text.

### ISSUE THREAD

**Issue by AJolly** [aedocw/epub2tts#276]
Since we are generating the audio, it'd be great if we could either 
1) output a Epub3 book with synchronized audio/text, or 
2) output the data to make it easier for other tools to create the Epub3.

Example: https://github.com/r4victor/syncabook
This will take the audio + text, and attempt to determine the synchronization data, and then combines the data to generate an epub3. 
The downside is its resource intensive.

**Comment by aedocw** [comment]
This was discussed in the past, see https://github.com/aedocw/epub2tts/issues/120 for a previous discussion.

At this point the best approach would be to generate the audiobook, then use [Storyteller](https://smoores.gitlab.io/storyteller/) or [syncabook](https://github.com/r4victor/syncabook) to create the EPUB3 version.

I won't have the time to do this work but would be happy to review PRs if someone else wants to take it on.
