### ISSUE TITLE
Make an epub2tts service with an API

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#28]
Make this so it can run as a service with an API, to allow for a future enhancement that adds a web UI so the service and UI can be run easily under docker or docker-compose.

Proposed API endpoints:
/upload/ - for uploading an epub file
/list/ - list available epub files
/scan/ - print first few lines of each chapter
/read/ - create m4b file
/download/ - for downloading completed m4b files
/delete/ - for deleting epub or m4b files

**Comment by aedocw** [comment]
Really need to clean everything up and use classes before trying to make an API for this. Will do that first, then probably use flask to serve API endpoints.

**Comment by aedocw** [comment]
Might end up just going easy-mode and using gradio (https://www.gradio.app/guides/quickstart) which would provide a web interface with minimal changes to existing code.

**Comment by rejuce** [comment]
shouldnt there be a /convert  and /status endopoint?
