### ISSUE TITLE
Crash if sentence is too long

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#31]
Some books seem to cause the sentence segmenter TTS uses (https://pypi.org/project/pysbd/) to fail to actually detect the end of the sentence. I can't tell what is causing this, but then the resulting sentence is very long as it's made up of multiple sentences strung together. That in turn causes epub2tts to get killed due to exceeding available memory.

Because this is external to epub2tts (and even external to coqui TTS) I don't think there's much I can do about it. Logging the bug here though in case anyone else runs into this. Best way to tell is to look at the output where it says "> Text splitted to sentences." followed by the list containing the sentences to be read. If you look through that you'll probably find one sentence that is enormously long. As of right now that just means this is a book that can't be turned into an m4b.

**Comment by aedocw** [comment]
FIX - convert book to TEXT. Maybe not the most elegant, but you can use Calibre to easily convert an epub to txt, and at least for the one book that was reliably causing this problem, that fixed it.

**Comment by danielw97** [comment]
Hi there,
Here's hoping this doesn't reopen the issue, although just to say that I'm consistently having this problem with epubs for some reason.
This is an exceptional project and is something I've been looking for for ages and full marks to you for the work you've done, however is there anything I might be able to do to track down this bug and perhaps solve it?
Converting to text is no problem, however some of the books I'm trying to run through are quite long and having chapter markers is a big plus.
Thanks in advance, and no problem if this is something that's not easily fixable.
