### ISSUE TITLE
Extract epub metadata

### ISSUE THREAD

**Issue by tverona1** [aedocw/epub2tts#49]
It would be useful to extract epub metadata and add these as tags to the generated audio file.

Also, it would be nice to be able to specify bitrate of the audio file.

**Comment by aedocw** [comment]
These are two really good suggestions, thanks! I'll see if I can poke at this soon.

**Comment by aedocw** [comment]
Really appreciate the suggestions here Tomer, they turned out to be really quick and easy to implement. I really like having the title and author show up properly, honestly don't know why I hadn't thought of that myself!

**Comment by tverona1** [comment]
Awesome, thank you!
