### ISSUE TITLE
Guide with Mac and python 3.

### ISSUE THREAD

**Issue by liangliao-igc** [aedocw/epub2tts#56]
Thanks for your greak work!

It really helps.

But I am wondering how to use it on Mac with python 3.12.0. and pip 3?

Can you provide an example?

There is what I tried:

1. Follow the steps at: https://github.com/aedocw/epub2tts#mac-installation
2. But I used the pip3 to install, rather than pip because I don't have pip.
3. and it shows me an error:
<img width="929" alt="image" src="https://github.com/aedocw/epub2tts/assets/145333406/55d518d4-679a-4c82-9db0-4ff4bd0725a4">

Thanks!!

**Comment by aedocw** [comment]
Coqui-TTS requires python < 3.12, so you can use up to Python v3.11. I've updated the instructions to use that version (though it will work with python >= 3.9, < 3.12).

Regarding pip vs pip3, if you're on a system that has only python3 installed I believe pip3 is aliased to pip? Regardless though, in the instructions, anywhere you see "pip" can safely be replaced with "pip3".
