### ISSUE TITLE
how to launch program

### ISSUE THREAD

**Issue by unifirer** [aedocw/epub2tts#97]
when i type 

epub2tts new 1.txt   --xtts sample-1.wav

into powershell i get

The term 'epub2tts' is not recognized as the name of a cmdlet, function, script file, or operable program.

please help, thank you

**Comment by danielw97** [comment]
Hi there,
aedocw may have more info than I do, however as someone else running this great utility on windows here's some advice that I'm personally following.
You have a few options on how to install this,as it's a python package.
Firstly, you can install it in your base environment although that may conflict with other packages you've installed.
I'm personally running this in a venv that way I can ensure all the requirements are correct and that nothing is conflicted.
After activating the venv, you simply have to type pip install . and then you can call epub2tts normally.
Please note however that you have to activate the venv each time you want to use it.
Hth a bit.

**Comment by aedocw** [comment]
Happy to try to help, what steps have you done so far in powershell? (i.e. cloned the repo, made and activated a virtual environment, ran pip install, etc).

Also I'll note that you are trying to call "new 1.txt" as the file name to read, but that won't work. If you are using a text or epub file with a space in the file name, you will need to put that in quotes, so your command would look like:
epub2tts "new 1.txt" --xtts sample1.wav

**Comment by unifirer** [comment]
> Hi there, aedocw may have more info than I do, however as someone else running this great utility on windows here's some advice that I'm personally following. You have a few options on how to install this,as it's a python package. Firstly, you can install it in your base environment although that may conflict with other packages you've installed. I'm personally running this in a venv that way I can ensure all the requirements are correct and that nothing is conflicted. After activating the venv, you simply have to type pip install . and then you can call epub2tts normally. Please note however that you have to activate the venv each time you want to use it. Hth a bit.

hey i went to ur profile to give u some coffees but u dont have a link, however u opened the same issues as i did on the coqui page haha, i went from 4.5hrs of xtts to 250 words too, i thought it was the other dependencies. so i came here for another solution and met u haha

**Comment by aedocw** [comment]
The full command, run from within the epub2tts directory, would be:

`pip install .`

(note the period at the end)

Sounds like you got it going though, that's great news!

**Comment by unifirer** [comment]
> Happy to try to help, what steps have you done so far in powershell? (i.e. cloned the repo, made and activated a virtual environment, ran pip install, etc).
> 
> Also I'll note that you are trying to call "new 1.txt" as the file name to read, but that won't work. If you are using a text or epub file with a space in the file name, you will need to put that in quotes, so your command would look like: epub2tts "new 1.txt" --xtts sample1.wav

omg its the maker of the this program, i followed [danielw97](https://github.com/danielw97)'s instructions and it works now, i didnt know i had to pip install despite installing all the other github programs, they all told me to install in pip in the instructions haha. i only follow instructions and use gui. 

thank you for the space tip. program is working now, however it seems like the program cant read the qoute sign: ”        

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 48: character maps to <undefined>

pos 47-50 is a qoute mark  ”

**Comment by unifirer** [comment]
> The full command, run from within the epub2tts directory, would be:
> 
> `pip install .`
> 
> (note the period at the end)
> 
> Sounds like you got it going though, that's great news!



> The full command, run from within the epub2tts directory, would be:
> 
> `pip install .`
> 
> (note the period at the end)
> 
> Sounds like you got it going though, that's great news!

wow python has insanely confusing syntax, its confusing because full stop is a part of normal speech, i notice u also dont have a tip page. even tho im from poor NZ, ill be glad to buy u 2 coffees

**Comment by aedocw** [comment]
Huh that's weird. For now I would suggest renaming the source text file to a filename with no spaces, just to get past this. I did not get any unicode errors in my testing, but I'm running it on macOS and Linux. I'll try to make time to run this on a windows machine so I can see what you're running into.

So cool that you're in NZ! I've been once and had a fantastic time, love your country. I'll try to visit again some time and you can buy me a coffee there, thanks!

**Comment by unifirer** [comment]
i can see how much trouble development is, so many small things a human can see right through but computers cant.

every1 here wants to leave because we are so poor haha, min wage is <15USD and rent is more than US and 95% jobs are min wage or worse(training wage is lower), higher income and sales tax too,   =(      and we have to pay big fees for shipping computer components and clothes here, 0 production for either here

**Comment by aedocw** [comment]
Ugh yeah that's rough about the wages, I hadn't realized that.

Definitely reach out if you have any problems I can help out with - take care!

**Comment by aedocw** [comment]
Closing this as I believe you're able to launch and run everything now. If there are other issues, please feel free to open new ones. Thanks for using it!
